name: qrcode-generator
base: core20
version: '1.0.0'
summary: Allow generating QR codes from user-inputted text
description: |
  A desktop application developed in Golang using the Fyne framework that allows generating QR codes from user-inputted text. Additionally, generated QR codes can be saved in PNG or JPG formats.

grade: stable
confinement: strict

apps:
  qrcode-generator:
    command: gui-qrcode-generator
    desktop: share/applications/qrcode-generator.desktop
    plugs:
      - network                # Grants network access
      - home                   # Grants access to user's home directory

parts:
  qrcode-generator:
    source: https://github.com/stescobedo92/gui-qrcode-generator  # Keep the URL
    source-type: git  # Add this line
    plugin: go
    build-packages:
      - gcc
      - pkg-config