name: qrcode-generator
base: core22
version: '1.0.0'
summary: Allow generating QR codes from user-inputted text
description: |
  A desktop application developed in Golang using the Fyne framework that allows generating QR codes from user-inputted text. Additionally, generated QR codes can be saved in PNG or JPG formats.
grade: stable
confinement: strict

apps:
  qrcode-generator:
    command: bin/gui-qrcode-generator
    desktop: usr/share/applications/qrcode-generator.desktop
    plugs:
      - network
      - home
      - desktop
      - x11
      - opengl
      - wayland

parts:
  qrcode-generator:
    plugin: go
    source: https://github.com/stescobedo92/gui-qrcode-generator
    source-type: git
    go-buildtags: [fyne]
    build-snaps:
      - go
    stage-packages:
      - libgl1
      - libx11-6
      - libxrandr2
      - libxxf86vm1
      - libxcursor1
      - libxinerama1
      - libxi6
      - libxext6
      - libxft2
    build-packages:
      - gcc
      - pkg-config
      - libx11-dev
      - libxrandr-dev
      - libxxf86vm-dev
      - libgl1-mesa-dev
      - libxcursor-dev
      - libxinerama-dev
      - libxi-dev
      - libxext-dev
      - libxft-dev
    override-build: |
      export CGO_ENABLED=1
      export GOPATH=$SNAPCRAFT_PART_BUILD/go
      export PATH=$GOPATH/bin:$PATH

      # Get dependencies
      go get -v ./...

      # Build the application
      go build -v -o gui-qrcode-generator

      # Create necessary directories
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications/

      # Copy binary
      cp gui-qrcode-generator $SNAPCRAFT_PART_INSTALL/bin/

      # Copy existing .desktop file
      cp share/applications/qrcode-generator.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/

  desktop-resources:
    plugin: dump
    source: snap/gui/
    organize:
      'qr-code-snap-icon.png': usr/share/icons/qr-code-snap-icon.png

  cleanup:
    after: [qrcode-generator]
    plugin: nil
    override-prime: |
      set -eux
      for lib in \
        usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0 \
        usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2 \
        usr/lib/x86_64-linux-gnu/libXft.so.2.3.4 \
        usr/lib/x86_64-linux-gnu/libXi.so.6.1.0 \
        usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0 \
        usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0 \
        usr/lib/x86_64-linux-gnu/libicuio.so.70.1 \
        usr/lib/x86_64-linux-gnu/libicutest.so.70.1; do
          if [ -f "$SNAPCRAFT_PRIME/$lib" ]; then
            rm "$SNAPCRAFT_PRIME/$lib"
          fi
      done
