name: qrcode-generator
base: core22
version: '1.0.0'
summary: Allow generating QR codes from user-inputted text
description: |
  A desktop application developed in Golang using the Fyne framework that allows generating QR codes from user-inputted text. Additionally, generated QR codes can be saved in PNG or JPG formats.
grade: stable
confinement: strict

apps:
  qrcode-generator:
    command: bin/gui-qrcode-generator
    desktop: share/applications/qrcode-generator.desktop
    plugs:
      - network
      - home
      - desktop
      - x11
      - opengl
      - wayland

parts:
  qrcode-generator:
    plugin: go
    source: https://github.com/stescobedo92/gui-qrcode-generator
    source-type: git
    build-snaps:
      - go
    stage-packages:
      - libgl1
      - libx11-6
      - libxrandr2
      - libxxf86vm1
      - libxcursor1
      - libxinerama1
      - libxi6
      - libxext6
      - libxft2
    build-packages:
      - gcc
      - pkg-config
      - libx11-dev
      - libxrandr-dev
      - libxxf86vm-dev
      - libgl1-mesa-dev
      - libxcursor-dev
      - libxinerama-dev
      - libxi-dev
      - libxext-dev
      - libxft-dev
    override-build: |
      export CGO_ENABLED=1
      # Ensure GOPATH is set correctly
      export GOPATH=$SNAPCRAFT_PART_BUILD/go
      export PATH=$GOPATH/bin:$PATH
      
      # Get dependencies
      go get -v ./...
      
      # Build the application
      go build -v -o gui-qrcode-generator
      
      # Create necessary directories and copy files
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp gui-qrcode-generator $SNAPCRAFT_PART_INSTALL/bin/