name: qrcode-generator
base: core22
version: '1.0.0'
summary: Generador de códigos QR a partir de texto ingresado por el usuario
description: |
  Una aplicación de escritorio desarrollada en Golang usando el framework Fyne que permite generar códigos QR a partir de texto ingresado por el usuario. Además, los códigos QR generados pueden guardarse en formatos PNG o JPG.
grade: stable
confinement: strict

apps:
  qrcode-generator:
    command: bin/gui-qrcode-generator
    desktop: usr/share/applications/qrcode-generator.desktop
    plugs:
      - network
      - home
      - desktop
      - x11
      - opengl
      - wayland
    environment:
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/dri

parts:
  qrcode-generator:
    plugin: go
    source: https://github.com/stescobedo92/gui-qrcode-generator
    source-type: git
    build-snaps:
      - go
    stage-packages:
      - libgl1
      - libgl1-mesa-glx        # Agregado
      - libgl1-mesa-dri        # Agregado
      - libx11-6
      - libxrandr2
      - libxxf86vm1
      - libxcursor1
      - libxinerama1
      - libxi6
      - libxext6
      - libxft2
    build-packages:
      - gcc
      - pkg-config
      - libx11-dev
      - libxrandr-dev
      - libxxf86vm-dev
      - libgl1-mesa-dev
      - libxcursor-dev
      - libxinerama-dev
      - libxi-dev
      - libxext-dev
      - libxft-dev
    override-build: |
      export CGO_ENABLED=1
      export GOPATH=$SNAPCRAFT_PART_BUILD/go
      export PATH=$GOPATH/bin:$PATH

      # Obtener dependencias
      go get -v ./...

      # Compilar la aplicación
      go build -v -o gui-qrcode-generator

      # Crear directorios necesarios
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/dri/

      # Copiar el binario
      cp gui-qrcode-generator $SNAPCRAFT_PART_INSTALL/bin/

      # Copiar el archivo .desktop existente
      cp share/applications/qrcode-generator.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/

      # Copiar los controladores DRI
      cp /usr/lib/x86_64-linux-gnu/dri/* $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/dri/

  desktop-resources:
    plugin: dump
    source: snap/gui/
    organize:
      'qr-code-snap-icon.png': usr/share/icons/qr-code-snap-icon.png

  cleanup:
    after: [qrcode-generator]
    plugin: nil

    override-prime: |
      set -eux
      # No es necesario realizar limpieza adicional ya que hemos copiado los controladores DRI necesarios
